# Generated by Django 5.1 on 2025-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('NSS', 'NSS'), ('Full-time', 'Full-Time'), ('Intern', 'Intern'), ('Contractor', 'Contractor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unique_id',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
